name: test

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build_and_test:
    name: Build and test on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-lastest, macos-latest, windows-latest]
        compiler: [g++10]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          cmake --build .
      - name: test
        run: ctest
        working_directory: build
